name: nuclei_segmentation
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - opencv-python
    - numpy<2
    - stardist
    - tensorflow-cpu
    - git+https://github.com/lettlini/core-data-utils
    - toml
