name: nuclei_segmentation_cellpose
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - opencv-python
    - numpy<2
    - cellpose
    - git+https://github.com/lettlini/core-data-utils
    - toml
