name: annotate_D2min
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - tqdm
    - numpy<2
    - scipy
    - networkx
    - git+https://github.com/lettlini/core-data-utils
