name: annotate_graph_theoretical_observables
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - opencv-python
    - tqdm
    - numpy<2
    - git+https://github.com/lettlini/core-data-utils
