name: calculate_local_density
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - opencv-python
    - tqdm
    - numpy
    - git+https://github.com/lettlini/core-data-utils
